monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!import"]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!import"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!import"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            channels: ["!import"]
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        import_log:
            type: stream
            path: "%kernel.logs_dir%/import.log"
            level: info
            channels: ["import"]
